### ISSUE TITLE
Trakt.tv integration

### ISSUE THREAD

**Issue by pistiolasm** [abricot/webinterface.arch#1]
Hi guys, great work! I would like to see two things in the future, _trakt.tv_ and _Genesis_ support!

**Comment by nicolasabric** [comment]
Hi pistiolasm I had a look at http://trakt.tv/ this morning and especially the API they provide. From what I can tell the integration can be very deep like for example:
- Display a calendar view based on your profile
- See your friend collections/status
- Display history hisory 
- etc

or a bit more simple :
- Sending a check-in request when Arch start to play an episode/movie

As I am new to this service it s a bit difficult for me to know what would make more sense to implement. I would greatly appreciate if you can share your view/needs on this ;) 

For Genesis same story never used it and did not manage to find a good documentation just yet. This one will require a bit more time but again your view/requirements on this is welcome.

**Comment by pistiolasm** [comment]
HI @nicolasabric,

Thank you for your reply. Personally I believe that it would be nice to display your [Upcoming schedule](http://docs.trakt.apiary.io/#reference/calendars), _TV/Movie collection (wish list)_ using their [Sync](http://docs.trakt.apiary.io/#reference/sync/stop-or-finish-watching-in-a-media-center) method, and be able to play a movie directly from there. Once you play it should mark it as _watched_ using their [scrobbling](http://docs.trakt.apiary.io/#reference/scrobble/stop-or-finish-watching-in-a-media-center) method. 

I believe that the trakt integration will make a lot of people to use this web interface because a lot of them keep track of their movies and collection using trakt.tv. This would be the first web interface that you have this feature.

Now, [Genesis](https://github.com/lambda81/lambda-addons/tree/master/plugin.video.genesis) is a great addon, well known to the Kodi community. You can stream Movies and TV shows directly from there and it has trakt.tv integration as well. So imagine that you could play a movie from your web interface, mark it as watched, and then open it in Genesis.

**Comment by nicolasabric** [comment]
Hi @pistiolasm,

I started the integration of Trakt but as of now it seems that there is an issue with their oauth. I just contacted Trakt support to see if this is indeed a real issue and if they can fix it. I will continue to investigate on my side and see if I can by pass this limitation.

**Comment by pistiolasm** [comment]
Hi @nicolasabric,

Great. I hope everything works out! With trakt.tv integration it will be a killer web interface!

**Comment by pistiolasm** [comment]
Hi @nicolasabric, Let me know if you want me to test anything :+1:

**Comment by nicolasabric** [comment]
Hi @pistiolasm, 

Could you please test this version https://db.tt/PhQBZXqy

FYI : 
- The add-on will work on Kodi Isengard (15.0+) as they did some changes regarding web interfaces. If you need a version for Helix ping me.
- You can configure Trakt from the settings screen. A refresh of the page may be needed the first time.
- If you do have the Trakt plugin activated on KODI I encourage you to de-activate the auto scrobbling from Arch. If you leave it both Arch and Trakt plugin will send scrobble events. Not very optimal ;)
- You can use the following video plugin for external sources : 
  - plugin.video.youtube (default)
  - plugin.video.pulsar
  - plugin.video.genesis 

Obviously you know what you are doing if you use one of the 2 last ones. 

Side note : Unfortunately for Genesis integration I did not managed to auto play the movie/episode. When using it it will automagically open genesis to the dialog where you can select the movie/episode. 

Any feedback is of course more than welcome.

**Comment by pistiolasm** [comment]
Hi @nicolasabric, This is GREAT! Exactly I was looking for. Great integration with trakt.tv :+1:. Also i believe its okay that it does not work fully with Genesis! 

A few things that I would recommend:
- I tested it with Chrome (Version 44.0.2403.155) and it does not render the html. It worked with Internet Explorer.
- The cover of a movie/show is a little big and it hides useful information.

Other than that great work. I believe that if you publish it on the official Kodi repository, you will have a great number of users using it!

Thanks,
Miltiadis

**Comment by nicolasabric** [comment]
@pistiolasm thanks for the super quick feedback. 
- For Chrome : Super strange I have the exact same version on my Mac and everything seems ok. Funny enough I never tested Arch with IE and apparently it works there. Do you have any error in the dev tools. While having Arch tab focused you can open the dev tools by hiting F12. I am interested by anything that would be under the console tab.
- For the cover : By any chance would you mind telling me the screen resolution of the device you used.

For both issues if you can make screenshots it will surely ease the investigation. In the mean time I will try to reproduce both issues on my old win PC.

**Comment by pistiolasm** [comment]
@nicolasabric here are the two images:

The first one is the 3 errors that I see and the second is the cover, using a 1600x900 screen.
![errors](https://cloud.githubusercontent.com/assets/4142983/9290717/c980e70c-436a-11e5-8cc3-0685dcf8b019.PNG) 
![screenshot](https://cloud.githubusercontent.com/assets/4142983/9290718/c9886bd0-436a-11e5-98d7-1dac19655bfd.PNG)

**Comment by nicolasabric** [comment]
@pistiolasm Could you try with this version https://db.tt/7Notu1cY. Cover issue should be fixed. As per the Chrome issue I did some tests on my laptop running windows 8 and latest Chrome and did not experienced it. 

Things I can think of :
- Issue with browser cache, try cleaning it
- Some files were not properly loaded. Could you please refresh the page while having the dev tools open and tell me if you do have files not found 404 in the network tab
- Some Chrome add-ons interfering in some ways. Try to launch chrome in private mode (ctrl+shift+n) and browse to Arch.
- Could you try with firefox see if the issue exists there as well?

I will have other windows PC at work next week I ll try there as well. Quick remark I noticed that the url you used in the IE screenshot is a bit strange. Was osmc.local/addons/webinterface.arch directly pointing to the host running Kodi ? FYI I m directly using  the IP of my PC runing Kodi something like http://192.168.0.5. Don t know if it can have an impact.

**Comment by pistiolasm** [comment]
@nicolasabric I tried it from a different laptop using chrome and it worked. I removed an extension from mine and now it works. Great work!!! 

FYI, it would be great to have the same for movies! Also it would be awesome to be able to add to lists, collection, and check in from the web interface! Just like Trakt.tv does on their website. :-)

![capture](https://cloud.githubusercontent.com/assets/4142983/9291732/c22b5c2e-439e-11e5-8302-975cb824f10d.PNG)

**Comment by nicolasabric** [comment]
@pistiolasm sorry for the late reply. Add to list/collection and check-in are under investigation but no luck till now. If you are interested I just released version 2.0.1 it is not yet on the official repo and therefore you will have to manually install it. You need this version to continue using genesis (5.0.0 and above) with Arch. Version 2.0.1 can be found here https://db.tt/hjZ8hCyc. Feedbacks are more than welcome as always ;)

**Comment by nicolasabric** [comment]
@pistiolasm version 2.0.2 is now available on Kodi Repo. This version add trakt actions such as add to history, watchlist and collection. I will then close this issue as most of the features requested are now available. Cheers Nico
