### ISSUE TITLE
Controls are not displayed when there is a background image

### ISSUE THREAD

**Issue by NerosTie** [abricot/webinterface.arch#10]
When there is a background image in "recently added" menus, the controls from the bottom right menus (the humburger and the speaker) are hidden because they are displayed under the background image.

![screenshot_20160110_201003](https://cloud.githubusercontent.com/assets/4572452/12223408/14ad8344-b7d7-11e5-9818-84352672268e.png)

But, if I block the background image, everything is ok:

![screenshot_20160110_200857](https://cloud.githubusercontent.com/assets/4572452/12223416/2c2117fc-b7d7-11e5-8315-e07c95e6d4ec.png)

Tested with Chrome, Firefox (desktop and mobile for both) and Vivaldi: same result.

**Comment by nicolasabric** [comment]
@NerosTie good one. I will provide a fix asap ;)
