### ISSUE TITLE
Disable remote control

### ISSUE THREAD

**Issue by nour-elghareeb** [abricot/webinterface.arch#20]
Hello,

First of all, Thank you for arch interface. It is really great.

Second, Is there a way to disable the remote control functions and make the interface view only? I need to share the library to some friends without the ability to control kodi.

Thank you once more.

**Comment by JamesGKent** [comment]
i can see why you might want that, but when you think about it that is a significant amount of work, as you would have to disable and or remove all the controls for that, so you have the bar at the bottom, the sidebar, and on every media page there is the play/queue buttons as well. as there are alternative ways of sharing your library there may not be much demand for this.
see here:
http://forum.kodi.tv/showthread.php?tid=182183
but note that one is only for movies and not TV series

**Comment by nour-elghareeb** [comment]
I totally understand. I'll have a look on that alternative.
Thanks for your reply and your time.
