### ISSUE TITLE
Kodi 15

### ISSUE THREAD

**Issue by damianorenfer** [abricot/webinterface.arch#3]
Hi your web interface looks great! Unfortunately, it is not Kodi 15 compatible. Do you plan to port it to Kodi 15 ?

**Comment by nicolasabric** [comment]
@damianorenfer yes validation is under way since last week. I m hopping that it will be validated in the coming days but if you want you can already get it from here https://db.tt/zDZpWIiB. Once downloaded just use install from zip file functionality from System > Add-ons.

Cheers,
Nico

**Comment by damianorenfer** [comment]
Ok thanks, I will give it a try! :smiley:
