### ISSUE TITLE
Some pages stuck on loading message

### ISSUE THREAD

**Issue by CaptInsano** [abricot/webinterface.arch#4]
Whenever I am on the following pages, I just get a "LOADING" message and no Movies/TV Shows:

Movies/Recently Added
Movies/ All Movies
TV Shows/Recently Added Episodes
TV Shows/All Shows

![capture](https://cloud.githubusercontent.com/assets/332478/9644670/5cdcef34-51bf-11e5-8aae-0bca7c2ef240.PNG)

I do get images and info on:

Movies/Discover
TV Shows/Discover

![capture2](https://cloud.githubusercontent.com/assets/332478/9644758/c49af15c-51bf-11e5-9251-e7661d3880a8.PNG)

I am using this plugin from the Official Kodi Repo (v2.0.0 as of time of writing). 

I have left all settings default:
Host IP: Correct
Webserver Port: 80 (Correct)
Api Port: 9090 (I assume correct??)

I have successful authenticated with my trakt account.

I am currently using Firefox 40.0.3 (latest), I have cleared cache, tried private mode and also tried Chrome 45.0.2454.85 (latest) but always the above problems.

Any advise on a fix?

NOTE: I have no such problems with the default web interface of Chorus web interface.

Thanks!!

**Comment by nicolasabric** [comment]
@CaptInsano from the screenshots you shared I can see that the connection with Kodi does not seem to be up (red square top right of your screen). Could you please check if you do have the following options checked in your settings under Services > Remote control :
- Allow remote control by programs on this system
- Allow remote control by programs on other systems

![screen shot 2015-09-03 at 08 34 42](https://cloud.githubusercontent.com/assets/4771275/9652765/6d9b536a-521e-11e5-849c-32078fc8059b.png)

If it is not the case check them and restart KODI. It should work after that ;).

**Comment by CaptInsano** [comment]
I already have those settings set:

![screenshot000](https://cloud.githubusercontent.com/assets/332478/9666083/fca8d7ba-526b-11e5-9903-8f9b1f5bcad0.png)

I have also tried disabling, re-enabling both options and rebooting. No improvement in the situation.

Any other ideas?
I am using OpenElec 6b4 (latest) based on Kodi 15.1 BTWs

**Comment by nicolasabric** [comment]
Could you please open the firefox dev tools then go to the console tab and copy paste what you see on screen. As an example running the same ff version as you on my Mac I get the following 
![screen shot 2015-09-03 at 20 47 53](https://cloud.githubusercontent.com/assets/4771275/9667621/1bfe8248-527d-11e5-8761-403afe95c75d.png)

and apparently everything is behaving as expected. 

The issue might also be related to the network itself and therefore would you mind answering those questions:
- Are you using the IP of your host or its network name?
- Are the PC running the web interface and KODI machine on the same local area network? Or are you going through internet?

PS:  To open the dev tools right click anywhere on the page and then select inspect element.

**Comment by CaptInsano** [comment]
Output of Firefox Dev Console:

http://pastebin.com/kJutWLFt

See Pic:

![capture](https://cloud.githubusercontent.com/assets/332478/9668144/bf53f78a-5277-11e5-91eb-dec8a62f6205.PNG)

As you can see KODI and Arch are on the same machine and I am using the IP address of the KODI/Arch machine to access it.

**Comment by nicolasabric** [comment]
I uploaded a newer version of Arch here https://db.tt/8wHqODEJ. It is still a beta version but I have fixed the web socket url scheme issue I saw in your log file. It may fix the issue but not sure. Could you please give it a try? To install just go to Settings >  Add-ons > Install from zip file and select the downloaded zip file.

If issue persists would you mind share your console output again. Thks ;)

**Comment by CaptInsano** [comment]
Working!! 

Good man!!

**Comment by nicolasabric** [comment]
Glad to hear it :) You are now officially the first user of version 2.0.2 :D. As said some new features might still be a bit buggy in this version. If you find bugs do not hesitate to communicate them. FYI I will try to finalize this version ASAP and ask for a repository update afterward.
